//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Ogrenci_kayit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Not
    {
        public int NotId { get; set; }
        public Nullable<int> OgrenciID { get; set; }
        public Nullable<int> DersID { get; set; }
        public Nullable<int> not1 { get; set; }
        public Nullable<int> not2 { get; set; }
    
        public virtual TBL_Dersler TBL_Dersler { get; set; }
        public virtual TBL_Ogrenci TBL_Ogrenci { get; set; }
    }
}
